"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_base)\
$os\
$username\
$sudo\
[](bg:color_surface0 fg:color_base)\
$directory\
[](fg:color_surface0 bg:color_surface1)\
$git_branch\
$git_status\
[](fg:color_surface1 bg:color_overlay1)\
$docker_context\
$conda\
[](fg:color_overlay1 bg:color_subtext1)\
[  ](fg:color_subtext1)\
$line_break$character
"""
right_format = """
$git_metrics\
$git_state\
$status\
$line_break
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_rosewater = "#f5e0dc"
color_flamingo = "#f2cdcd"
color_pink = "#f5c2e7"
color_mauve = "#cba6f7"
color_red = "#f38ba8"
color_maroon = "#eba0ac"
color_peach = "#fab387"
color_yellow = "#f9e2af"
color_green = "#a6e3a1"
color_teal = "#94e2d5"
color_sky = "#89dceb"
color_sapphire = "#74c7ec"
color_blue = "#89b4fa"
color_lavender = "#b4befe"
color_text = "#cdd6f4"
color_subtext1 = "#bac2de"
color_subtext0 = "#a6adc8"
color_overlay2 = "#9399b2"
color_overlay1 = "#7f849c"
color_overlay0 = "#6c7086"
color_surface2 = "#585b70"
color_surface1 = "#45475a"
color_surface0 = "#313244"
color_base = "#1e1e2e"
color_mantle = "#181825"
color_crust = "#11111b"

[os]
disabled = false
style = "bg:color_base fg:color_subtext0"

[os.symbols]
Arch = "  "

[username]
show_always = true
style_user = "bg:color_base fg:color_subtext0"
style_root = "bg:color_base fg:color_red"
format = '[$user ]($style)'

[sudo]
disabled = false
symbol = " "
style = "bg:color_base fg:color_subtext0"
format = "[$symbol ]($style)"

[directory]
style = "bg:color_surface0 fg:color_subtext1"
read_only_style = "bg:color_surface0 fg:color_subtext1"
format = "[ $read_only]($read_only_style)[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = "󰉐 "

[git_branch]
always_show_remote = true
symbol = "󰊢 "
style = "bg:color_surface1 fg:color_text"
format = '[ $symbol$branch \(󰘿 $remote_branch\) ]($style)'

[git_status]
style = "bg:color_surface1 fg:color_text"
format = "[$all_status $ahead_behind]($style)"
conflicted = "[󱅜 $count](bg:color_surface1 fg:color_peach) "
ahead = "[ $count](bg:color_surface1 fg:color_sapphire) "
behind = "[ $count](bg:color_surface1 fg:color_maroon) "
diverged = "[󰦻 ](bg:color_surface1 fg:color_yellow) "
up_to_date = ""
untracked = "[ $count](bg:color_surface1 fg:color_pink) "
stashed = "[ $count](bg:color_surface1 fg:color_blue) "
modified = "[ $count](bg:color_surface1 fg:color_yellow) "
staged = "[󰄴 $count](bg:color_surface1 fg:color_blue) "
renamed = "[󰑕 $count](bg:color_surface1 fg:color_yellow) "
deleted = "[󰆴 $count](bg:color_surface1 fg:color_red) "

[git_metrics]
disabled = false
added_style = "bg:color_surface1 fg:color_green"
deleted_style = "bg:color_surface1 fg:color_red"
format = '[ ](fg:color_surface1)[[+$added]($added_style)/[-$deleted]($deleted_style)](bg:color_surface1)[](fg:color_surface1)'

[git_state]
style = "bg:color_surface1 fg:color_text"
format = '[ ](fg:color_surface1)[\($state($progress_current of $progress_total)\)]($style)[](fg:color_surface1)'

[docker_context]
symbol = " "
style = "bg:color_overlay1 fg:color_crust"
format = '[ $symbol$context ]($style)'

[conda]
style = "bg:color_overlay1 fg:color_crust"
format = '[ $symbol$environment ]($style)'

[status]
disabled = false
style = "bg:color_surface0 fg:color_subtext1"
symbol = " "
success_symbol = " "
format = '[ ](fg:color_surface0)[$symbol\($status\)]($style)[ ](fg:color_surface0)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:color_lavender)'
error_symbol = '[ ](bold fg:color_red)'
vimcmd_symbol = '[ ](bold fg:color_lavender)'
vimcmd_replace_one_symbol = '[ ](bold fg:color_peach)'
vimcmd_replace_symbol = '[ ](bold fg:color_peach)'
vimcmd_visual_symbol = '[ ](bold fg:color_yellow)'
