[config]
reload_apps = true
set_wallpaper = false
# wallpaper_tool = 'Swww'
# prefix = '@'
# swww_options = [
#     "--transition-type",
#     "center",
# ]
# run_after = [
#     [ "echo", "'hello'" ],
#     [ "echo", "'hello again'" ],
# ]

[config.reload_apps_list]
waybar = true
kitty = true
gtk_theme = true

[templates] # Another way
test1 = { input_path = '~/.config/waybar/template.style.css', output_path = '~/.config/waybar/style.css' }
