return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",

    config = function()
        local configs = require("nvim-treesitter.configs")
        configs.setup({
            auto_install = true,
            ensure_installed = {
                 "asm",
                 "bash",
                 "bibtex",
                 "c",
                 "cmake",
                 "cpp",
                 "diff",
                 "dockerfile",
                 "fish",
                 "git_config",
                 "git_rebase",
                 "gitattributes",
                 "gitcommit",
                 "gitignore",
                 "go",
                 "html",
                 "hyprlang",
                 "java",
                 "javascript",
                 "json",
                 "latex",
                 "lua",
                 "luadoc",
                 "luap",
                 "make",
                 "markdown",
                 "markdown_inline",
                 "matlab",
                 "mermaid",
                 "php",
                 "passwd",
                 "printf",
                 "python",
                 "r",
                 "regex",
                 "ruby",
                 "rust",
                 "sql",
                 "ssh_config",
                 "tmux",
                 "toml",
                 "vim",
                 "vimdoc",
                 "yaml",
                 "xml",
                 "zathurarc",
            },
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
            indent = {
                enable = true,
            },
        })
    end
}
