##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

windowrule = suppress_event maximize, match:class .* # You'll probably like this.
windowrule = opacity 0.85 override, match:class (kitty)
windowrule = opacity 0.85 override, match:class (foot)
windowrule = opacity 0.3 override, match:title (cava)

windowrule = float 1, match:workspace s[true]
windowrule = center 1, match:workspace s[true]
windowrule = size monitor_w*0.75 monitor_h*0.75, match:workspace s[true]

# Smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 20, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 20, match:float 0, match:workspace f[1]
